import requests
import openpyxl

# Define the base API URL
base_url = "https://security-cockpit.netcracker.com/api/v1"

try:
    # Read the buildid from the file generated by the POST script
    with open("source/createwb/cockpitparams/buildid.txt", "r") as buildid_file:
        buildid = buildid_file.read().strip()

    # Construct the URL for the GET request to retrieve the report in xlsx format
    get_report_url = f"{base_url}/getreport?buildid={buildid}&format=xlsx"

    # Send GET request to retrieve the report
    response = requests.get(get_report_url)

    if response.status_code == 200:
        print("GET request successful.")
        
        # Save the response content to an Excel workbook
        with open("workbook.xlsx", "wb") as excel_file:
            excel_file.write(response.content)
            
        print("Report saved as workbook.xlsx.")
    else:
        print("GET request failed. Status code:", response.status_code)

except FileNotFoundError:
    print("Buildid file not found. Run the POST script first.")
except requests.exceptions.RequestException as e:
    print("GET request error:", e)
