import requests
import time

# Define the base API URL
base_url = "https://security-cockpit.netcracker.com/api/v1"

try:
    # Read the buildid from the file generated by the POST script
    with open("source/createwb/cockpitparams/buildid.txt", "r") as buildid_file:
        buildid = buildid_file.read().strip()
        
    # Construct the URL for the GET request to check status report
    get_report_status_url = f"{base_url}/getreportstatus?buildid={buildid}"
    
    while True:
        # Send GET request to check status report
        status_response = requests.get(get_report_status_url)
        
        if status_response.status_code == 200:
            status_response_json = status_response.json()
            print("GET request successful.")
            print("Status Report:", status_response_json)
            
            pending = status_response_json.get('pending', 0)
            if pending == 0 or pending == 1:
                if pending == 1:
                    for _ in range(3):  # Hit 3 times to check if it becomes 0
                        time.sleep(2)  # Wait for 2 seconds
                        status_response = requests.get(get_report_status_url)
                        status_response_json = status_response.json()
                        pending = status_response_json.get('pending', 0)
                        if pending == 0:
                            print("Pending count became 0.")
                            break
                
                #print("Exiting the program.")
                break  # Exit the loop
                
            time.sleep(2)  # Wait for 2 seconds before the next iteration
            
        else:
            print("GET request for status report failed. Status code:", status_response.status_code)
            break
        
except FileNotFoundError:
    print("Buildid file not found. Run the POST script first.")
except requests.exceptions.RequestException as e:
    print("GET request error:", e)
