import requests

# Define the base API URL
base_url = "https://security-cockpit.netcracker.com/api/v1"

try:
    # Read the buildid from the file generated by the POST script
    with open("source/createwb/cockpitparams/buildid.txt", "r") as buildid_file:
        buildid = buildid_file.read().strip()
        
    # Construct the URL for the GET request to check status report
    get_report_status_url = f"{base_url}/getreportstatus?buildid={buildid}"
    
    # Send GET request to check status report
    status_response = requests.get(get_report_status_url)
    
    if status_response.status_code == 200:
        status_response_json = status_response.json()
        print("GET request successful.")
        print("Status Report:", status_response_json)
    else:
        print("GET request for status report failed. Status code:", status_response.status_code)
        
except FileNotFoundError:
    print("Buildid file not found. Run the POST script first.")
except requests.exceptions.RequestException as e:
    print("GET request error:", e)
